### ISSUE TITLE
Error building jq package on latest

### ISSUE THREAD

**Issue by mikoop79** [kjdev/php-ext-jq#13]
```bash
#40 2.651 checking whether to enable jq coverage support... no
#40 2.652 checking for jq files in default path... not found
#40 2.652 configure: error: Please reinstall the jq development files
------
executor failed running [/bin/sh -c git clone --depth=1 https://github.com/kjdev/php-ext-jq.git && cd php-ext-jq && phpize && ./configure && make && make install && printf "extension=jq.so\n; jq.display_errors=Off\n" > /usr/local/etc/php/conf.d/jq.ini && cd .. && rm -rf php-ext-jq]: exit code: 1
ERROR: Service 'app' failed to build : Build failed

```

Getting this error.  any ideas? all of a sudden failed. running via docker compose and on php 74

how to set the default path?

**Comment by kjdev** [comment]
Starting from version 0.2.0, the jq shared library is required.

Header files are also required for the build.

If you are using ubuntu, you can build it by installing the `libjq-dev` package.

**Comment by mikoop79** [comment]
@kjdev thanks,

so If I install the dev package I don't need to add a path via ./configure? 

if I do, can you provide an example?

**Comment by mikoop79** [comment]
@kjdev its ok. got it working.
